### ISSUE TITLE
unable to install this plugin in android 7.0.0 

### ISSUE THREAD

**Issue by krishnareddy1526** [dpa99c/phonegap-launch-navigator#203]
Failed to install 'uk.co.workingedge.phonegap.plugin.launchnavigator': Error: ENOENT: no such file or directory, open 'F:\GITLocal\DriverApp\platforms\android\AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.parseElementtreeSync (F:\GITLocal\DriverApp\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (F:\GITLocal\DriverApp\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (F:\GITLocal\DriverApp\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (F:\GITLocal\DriverApp\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\Anikini\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
(node:12404) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'F:\GITLocal\DriverApp\platforms\android\AndroidManifest.xml'

**Comment by dpa99c** [comment]
This is a bug in `cordova` / `cordova-android` and not specific to this plugin ([see here, for example](https://github.com/dpa99c/cordova-custom-config/issues/146)).

For future reference, I would have closed this issue anyway since you didn't fill out the issue template and provide the necessary information on your build environment - the error message and stack trace alone are not enough to diagnose a problem.
